baseURL: "https://youreawizard.netlify.app/"
languageCode: en-us
title: You're a Wizard
theme: hugo-ink
paginate: 5
copyright: © Aman Bhargava
pygmentsstyle: vs
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
googleAnalytics: UA-123-45
disqusShortname: youreawizard
params:
  avatar: https://i.imgur.com/zheWwPn.png
  disableDisqusTypes: page
  featherIconsCDN: yes
  mode: auto
  social:
    - icon: instagram
      name: instagram
      url: https://instagram.com/thedivtagguy
    - icon: twitter
      name: Twitter
      url: https://twitter.com/thedivtagguy
    - icon: rss
      name: RSS
      url: /index.xml
  subtitle: A few of the hundreds of emails I've received over the last 5 years from children around the world who believe that the website I made would really take them to Hogwarts. Sorry guys. *2004 signups and counting.*
menu:
  main:
    - name: All Emails
      url: /
      weight: 1
    - name: 🌟 Top Picks
      url: /categories/top-pick/
      weight: 2
    - name: What The Heck is Going On?
      url: http://theyellipages.in/issue7/#harry
      weight: 3
    - name: 📧 Get Your Own Letter
      url: http://hogwartsuk.weebly.com/admission.html
      weight: 4
taxonomies:
  tag: tags
  category: categories
